#!/bin/sh

# Get the current usage of CPU and memory
cpuUsage=$(top -b -n2 -p 1 | fgrep "Cpu(s)" | tail -1 | awk -F'id,' -v prefix="$prefix" '{ split($1, vs, ","); v=vs[length(vs)]; sub("%", "", v); printf "%s%.1f%%\n", prefix, 100 - v }')

# Print the usage
echo " 🚀 $cpuUsage "



